---
- name: Update new code and Restart the service
  hosts: all:
    vars:
      - app: httpd

  tasks:
  - name: Place custom HTML file:
    copy:
      src: /var/lib/jenkins/workspace/website-update/index.html
      dest: /var/www/html/index.html
    become: true

  - name: Start the services
    service:
      name: httpd
      state: restarted
      enabled: yes
    become: true